version: "3.8"

networks:
  devnet:
    name: devnet
    driver: bridge

services:
  devbox:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     GO_VERSION: "1.21.4"
    #     NODE_VERSION: "20.10.0"
    #     PHP_VERSION: "8.2"
    #     PYTHON_VERSION: "3.11"
    #     RUST_VERSION: "1.74.0"
    networks:
      - devnet
    volumes:
      - ../:/workspace
    command: sleep infinity
